module.exports = {
    trailingComma: 'es5',
    singleQuote: true,
    bracketSpacing: false,
    semi: true,
    useTabs: false,
    tabWidth: 4,
    printWidth: 80,
    quoteProps: 'as-needed',
    jsxSingleQuote: true,
    arrowParens: 'always',
    proseWrap: 'preserve',
    htmlWhitespaceSensitivity: 'css',
    endOfLine: 'auto',
};
